In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# Loading the necessary libraires

In [2]:
data=pd.read_csv('housing.csv') 
# Loading the data

In [3]:
data.head()
# Taking a look at the head of the data

RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [4]:
data.describe()
# Describing statisitical values about the data

RM       LSTAT     PTRATIO          MEDV
count  489.000000  489.000000  489.000000  4.890000e+02
mean     6.240288   12.939632   18.516564  4.543429e+05
std      0.643650    7.081990    2.111268  1.653403e+05
min      3.561000    1.980000   12.600000  1.050000e+05
25%      5.880000    7.370000   17.400000  3.507000e+05
50%      6.185000   11.690000   19.100000  4.389000e+05
75%      6.575000   17.120000   20.200000  5.187000e+05
max      8.398000   37.970000   22.000000  1.024800e+06

In [5]:
data.info()
#  Getting info about the data to check for null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   RM       489 non-null    float64
 1   LSTAT    489 non-null    float64
 2   PTRATIO  489 non-null    float64
 3   MEDV     489 non-null    float64
dtypes: float64(4)
memory usage: 15.4 KB


In [17]:
data_array=data.values
print(data_array)
# Converting data from csv to numypy

[[6.575e+00 4.980e+00 5.040e+05]
 [6.421e+00 9.140e+00 4.536e+05]
 [7.185e+00 4.030e+00 7.287e+05]
 ...
 [6.976e+00 5.640e+00 5.019e+05]
 [6.794e+00 6.480e+00 4.620e+05]
 [6.030e+00 7.880e+00 2.499e+05]]


In [7]:
print(data_array.shape)
# Printing the shape of the new 2-d array created

(489, 4)


In [8]:
data['RM'].nunique()

430

In [9]:
data['LSTAT'].nunique()

442

In [10]:
data['PTRATIO'].nunique()

44

In [11]:
data['MEDV'].nunique()
# Getting the number of unique values in all the columns to look for categorical data

228

In [12]:
data=data.rename(columns={'RM':'Avg No of Rooms','LSTAT':'% Lower status of population','PTRATIO':'Pupil Teacher Ratio','MEDV':'Median of OWner Occupied Home'})
data.head()
# Renaming the columns to be more descriptive

Avg No of Rooms  ...  Median of OWner Occupied Home
0            6.575  ...                       504000.0
1            6.421  ...                       453600.0
2            7.185  ...                       728700.0
3            6.998  ...                       701400.0
4            7.147  ...                       760200.0

[5 rows x 4 columns]

In [13]:
data.drop(columns=['Pupil Teacher Ratio'],inplace=True)
data.head()
# Dropping the column pupil teacher ration as it will not help us in predicting the price 

Avg No of Rooms  % Lower status of population  Median of OWner Occupied Home
0            6.575                          4.98                       504000.0
1            6.421                          9.14                       453600.0
2            7.185                          4.03                       728700.0
3            6.998                          2.94                       701400.0
4            7.147                          5.33                       760200.0

In [14]:
data.iloc[100:200,:]
# Getting the values between 100 and 200 of the dataset using slicing 

Avg No of Rooms  ...  Median of OWner Occupied Home
100            6.727  ...                       577500.0
101            6.781  ...                       556500.0
102            6.405  ...                       390600.0
103            6.137  ...                       405300.0
104            6.167  ...                       422100.0
..               ...  ...                            ...
195            6.162  ...                       506100.0
196            7.610  ...                       888300.0
197            7.853  ...                      1018500.0
198            5.891  ...                       474600.0
199            6.326  ...                       512400.0

[100 rows x 3 columns]

In [15]:
data[data['Avg No of Rooms']>=2]
# Getting only those data values in which avg no of rooms is greater than 2

Avg No of Rooms  ...  Median of OWner Occupied Home
0              6.575  ...                       504000.0
1              6.421  ...                       453600.0
2              7.185  ...                       728700.0
3              6.998  ...                       701400.0
4              7.147  ...                       760200.0
..               ...  ...                            ...
484            6.593  ...                       470400.0
485            6.120  ...                       432600.0
486            6.976  ...                       501900.0
487            6.794  ...                       462000.0
488            6.030  ...                       249900.0

[489 rows x 3 columns]

In [16]:
data[data['Median of OWner Occupied Home']>data['Median of OWner Occupied Home'].mean()]
# Gettin the values in which the median of Owner Occupied Home is greater than the average

Avg No of Rooms  ...  Median of OWner Occupied Home
0              6.575  ...                       504000.0
2              7.185  ...                       728700.0
3              6.998  ...                       701400.0
4              7.147  ...                       760200.0
5              6.430  ...                       602700.0
..               ...  ...                            ...
477            5.926  ...                       514500.0
478            5.670  ...                       485100.0
484            6.593  ...                       470400.0
486            6.976  ...                       501900.0
487            6.794  ...                       462000.0

[224 rows x 3 columns]

In [30]:
data.iloc[200:,0]
# Slicing the data so that we have the first column and the values from 200 onwards for that column


200    5.783
201    6.064
202    5.344
203    5.960
204    5.404
       ...  
484    6.593
485    6.120
486    6.976
487    6.794
488    6.030
Name: Avg No of Rooms, Length: 289, dtype: float64