In [33]:
import pandas as pd
df=pd.read_csv("housing.csv")
print(df.head(5))


      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0


In [28]:
from numpy import array
data=df.to_numpy()
print(data)

[[6.575e+00 4.980e+00 1.530e+01 5.040e+05]
 [6.421e+00 9.140e+00 1.780e+01 4.536e+05]
 [7.185e+00 4.030e+00 1.780e+01 7.287e+05]
 ...
 [6.976e+00 5.640e+00 2.100e+01 5.019e+05]
 [6.794e+00 6.480e+00 2.100e+01 4.620e+05]
 [6.030e+00 7.880e+00 2.100e+01 2.499e+05]]


In [14]:
X= data[:, :-1]
print(X)

[[ 6.575  4.98  15.3  ]
 [ 6.421  9.14  17.8  ]
 [ 7.185  4.03  17.8  ]
 ...
 [ 6.976  5.64  21.   ]
 [ 6.794  6.48  21.   ]
 [ 6.03   7.88  21.   ]]


In [16]:
X= data[:, :-2]
print(X)

[[ 6.575  4.98 ]
 [ 6.421  9.14 ]
 [ 7.185  4.03 ]
 [ 6.998  2.94 ]
 [ 7.147  5.33 ]
 [ 6.43   5.21 ]
 [ 6.012 12.43 ]
 [ 6.172 19.15 ]
 [ 5.631 29.93 ]
 [ 6.004 17.1  ]
 [ 6.377 20.45 ]
 [ 6.009 13.27 ]
 [ 5.889 15.71 ]
 [ 5.949  8.26 ]
 [ 6.096 10.26 ]
 [ 5.834  8.47 ]
 [ 5.935  6.58 ]
 [ 5.99  14.67 ]
 [ 5.456 11.69 ]
 [ 5.727 11.28 ]
 [ 5.57  21.02 ]
 [ 5.965 13.83 ]
 [ 6.142 18.72 ]
 [ 5.813 19.88 ]
 [ 5.924 16.3  ]
 [ 5.599 16.51 ]
 [ 5.813 14.81 ]
 [ 6.047 17.28 ]
 [ 6.495 12.8  ]
 [ 6.674 11.98 ]
 [ 5.713 22.6  ]
 [ 6.072 13.04 ]
 [ 5.95  27.71 ]
 [ 5.701 18.35 ]
 [ 6.096 20.34 ]
 [ 5.933  9.68 ]
 [ 5.841 11.41 ]
 [ 5.85   8.77 ]
 [ 5.966 10.13 ]
 [ 6.595  4.32 ]
 [ 7.024  1.98 ]
 [ 6.77   4.84 ]
 [ 6.169  5.81 ]
 [ 6.211  7.44 ]
 [ 6.069  9.55 ]
 [ 5.682 10.21 ]
 [ 5.786 14.15 ]
 [ 6.03  18.8  ]
 [ 5.399 30.81 ]
 [ 5.602 16.2  ]
 [ 5.963 13.45 ]
 [ 6.115  9.43 ]
 [ 6.511  5.28 ]
 [ 5.998  8.43 ]
 [ 5.888 14.8  ]
 [ 7.249  4.81 ]
 [ 6.383  5.77 ]
 [ 6.816  3.95 ]
 [ 6.145  6.86

In [42]:
df['New_col'] = 'default value'
print(df)

        RM  LSTAT  PTRATIO      MEDV        New_col
0    6.575   4.98     15.3  504000.0  default value
1    6.421   9.14     17.8  453600.0  default value
2    7.185   4.03     17.8  728700.0  default value
3    6.998   2.94     18.7  701400.0  default value
4    7.147   5.33     18.7  760200.0  default value
..     ...    ...      ...       ...            ...
484  6.593   9.67     21.0  470400.0  default value
485  6.120   9.08     21.0  432600.0  default value
486  6.976   5.64     21.0  501900.0  default value
487  6.794   6.48     21.0  462000.0  default value
488  6.030   7.88     21.0  249900.0  default value

[489 rows x 5 columns]


In [43]:
df['New_col2'] = '0'
print(df)

        RM  LSTAT  PTRATIO      MEDV        New_col New_col2
0    6.575   4.98     15.3  504000.0  default value        0
1    6.421   9.14     17.8  453600.0  default value        0
2    7.185   4.03     17.8  728700.0  default value        0
3    6.998   2.94     18.7  701400.0  default value        0
4    7.147   5.33     18.7  760200.0  default value        0
..     ...    ...      ...       ...            ...      ...
484  6.593   9.67     21.0  470400.0  default value        0
485  6.120   9.08     21.0  432600.0  default value        0
486  6.976   5.64     21.0  501900.0  default value        0
487  6.794   6.48     21.0  462000.0  default value        0
488  6.030   7.88     21.0  249900.0  default value        0

[489 rows x 6 columns]


In [26]:
df_new=df.rename(columns={"RM": "Room_Avg", "MEDV": "Median_Value"})
rm_medv=df_new.drop(columns=['LSTAT','PTRATIO'])
print(rm_medv)

     Room_Avg  Median_Value
0       6.575      504000.0
1       6.421      453600.0
2       7.185      728700.0
3       6.998      701400.0
4       7.147      760200.0
..        ...           ...
484     6.593      470400.0
485     6.120      432600.0
486     6.976      501900.0
487     6.794      462000.0
488     6.030      249900.0

[489 rows x 2 columns]
