In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot
df = pd.read_csv ('housing.csv')

arr=df.to_numpy()
print(arr)


[[6.575e+00 4.980e+00 1.530e+01 5.040e+05]
 [6.421e+00 9.140e+00 1.780e+01 4.536e+05]
 [7.185e+00 4.030e+00 1.780e+01 7.287e+05]
 ...
 [6.976e+00 5.640e+00 2.100e+01 5.019e+05]
 [6.794e+00 6.480e+00 2.100e+01 4.620e+05]
 [6.030e+00 7.880e+00 2.100e+01 2.499e+05]]


# New Section

In [ ]:
print(df)

        RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]


In [ ]:
print(np.delete(arr,2,axis=0))

[[6.575e+00 4.980e+00 1.530e+01 5.040e+05]
 [6.421e+00 9.140e+00 1.780e+01 4.536e+05]
 [6.998e+00 2.940e+00 1.870e+01 7.014e+05]
 ...
 [6.976e+00 5.640e+00 2.100e+01 5.019e+05]
 [6.794e+00 6.480e+00 2.100e+01 4.620e+05]
 [6.030e+00 7.880e+00 2.100e+01 2.499e+05]]


In [ ]:
df.rename(columns={'MEDV':'Value'},inplace=True)
print(df)


        RM  LSTAT  PTRATIO     Value
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]


In [ ]:
df_new=df.iloc[0:2,1:3]
print(df_new)

   LSTAT  PTRATIO
0   4.98     15.3
1   9.14     17.8
